config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  resources :high_scores, only: [:create, :index]
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
  validates :name, :score, presence: true
  validates :name, length: { minimum: 1, maximum: 12 }
  default_scope -> { order(score: :desc) }

  def score
    read_attribute(:score).to_s.rjust(4, '0')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
    @high_scores = HighScore.limit(10)
    render json: @high_scores
  end

  def create
    @high_score = HighScore.new(high_score_params)

    if @high_score.save
      render json: @high_score, status: :ok
    else
      render json: @high_score.errors.full_messages, status: :unprocessable_entity
    end
  end

  private
  def high_score_params
    params.require(:high_score).permit(:name, :score)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    @high_scores = HighScore.limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrappyBird</title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>© <a href="http://www.djc.space">David James Carter</a></footer>

</body>
</html>

<script>
  $(window).load(function () {
    var canvas = document.getElementById('game-canvas');
    var x = 432,
        y = 644;
    canvas.width = x;
    canvas.height = y;
    var ctx = canvas.getContext('2d');

    ctx.font = '28px "Press Start 2P"';
    ctx.fillStyle = "white";
    ctx.textAlign = "center";
    ctx.lineWidth = 2;
    ctx.strokeStyle = "#3e2500";

    var options = {
      ctx: ctx,
      width: x,
      height: y
    };
    var gameView = new CrappyBird.GameView(ctx);
  });
</script>

app/views/static_pages/_scoreboard.html.erb
<div id="scoreboard-container">
  <div class="game-over">Game Over!</div>
    <table class="scoreboard">
      <th colspan="2">High Scores</th>
      <% @high_scores.each do |score| %>
      <tr>
        <td><%= score.name %></td>
        <td><%= score.score %></td>
      </tr>
      <% end %>
    </table>

  <div class="user-score">
    Score:<span id="score"></span>
  </div>

  <%= render 'scoreboard_form' %>
</div>
<div class="restart">
  Restart?
</div>

app/views/static_pages/_scoreboard_form.html.erb
<div id="score-form-container">
  <form action="<%= high_scores_url %>" method="post" id="score-form">
    <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
    <input type="text" name="high_score[name]" placeholder="enter name here" id="input-name">
    <input type="hidden" name="high_score[score]" id="input-score">
  </form>
</div>

app/views/static_pages/root.html.erb
<div class="bg-image"></div>
<div class="phone-backdrop"></div>
<div id="main" class="container">
  <div class="landing press-start">press SPACE to start</div>
  <div class="hint">press 'f' to crap! (aim for the pipes!)</div>
  <div class="landing game-title">CrappyBird!</div>
  <%= render "scoreboard" %>
  <canvas id="game-canvas" moz-opaque></canvas>
  <div class="errors"></div>
</div>